server:
  port: 8080

spring:
  datasource:
    username: adminuser
    password: E3D5754D2D67C
    url: jdbc:mysql://192.168.68.209:3306/schedule?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.entity
  config-location: classpath:mybatis-config.xml
#showSql
logging:
  level:
    com:
      example:
        mapper : debug
swagger:
  basePackage: com.rdpass.dynamic.demo.controller

dynamic:
  jar: -file:/Users/guodongqing/workspace/ideaProjects/springboot-dynamic/springboot-dynamic-demo-ext/target/springboot-dynamic-demo-ext-1.0.0-BASE-SNAPSHOT.jar
  swagger:
    doc:
      package: com.rdpaas.demo.ext.controller